[package]
name = "mserver"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mscore.workspace = true
tokio.workspace = true
rusqlite.workspace = true
hmac.workspace = true
sha2.workspace = true
scrypt.workspace = true
aes-gcm.workspace = true
rand.workspace = true
base64.workspace = true
futures.workspace = true
num-bigint.workspace = true
num-traits.workspace = true
serde_json = "1"
ctrlc = "3"
rustls.workspace = true
tokio-rustls.workspace = true
rustls-pemfile.workspace = true

[dev-dependencies]
rcgen = { version = "0.13", default-features = false, features = ["ring", "pem"] }
