// parity-python.test.js - live Node <-> Python differential test.
//
// Re-verifies (without frozen fixtures) that the ms/ port is byte-for-byte
// equivalent to the Python reference on:
//   1. sim engine boards/states after click/flag/chord scripts
//   2. solver buildConstraints / deduce / frontierProbabilities / nonfrontierP
// on random mid-game boards (generated by the same gen_board() used by
// tools/analyze_diff.py).
//
// Skipped automatically when `python` is not on PATH or the reference modules
// cannot be imported.  The frozen fixtures (golden-*.json) still pin the
// Python results for environments without Python.

import { test } from "node:test";
import assert from "node:assert/strict";
import { checkPython, runSimDiff, runSolveDiff } from "../tools/parity-all.js";

const PY_AVAILABLE = checkPython();

test(
  "Node sim engine matches Python on boards + state (live)",
  { skip: PY_AVAILABLE ? false : "python + reference modules not available" },
  () => {
    const r = runSimDiff();
    assert.equal(
      r.failures,
      0,
      `${r.failures} sim mismatch(es) across ${r.scripts} scripts`,
    );
  },
);

test(
  "Node solver matches Python on cons/deduce/probs/nfp (live)",
  { skip: PY_AVAILABLE ? false : "python + reference modules not available" },
  () => {
    const r = runSolveDiff();
    assert.equal(
      r.failures,
      0,
      `${r.failures} solver mismatch(es) across ${r.boards} boards`,
    );
  },
);
