import { test } from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { SimBoard, Rng64, ZERO_SEED_FALLBACK } from "../core/sim-engine.js";

const here = path.dirname(fileURLToPath(import.meta.url));
const goldens = JSON.parse(
  fs.readFileSync(path.join(here, "fixtures", "golden-boards.json"), "utf8")
);

test("SimBoard matches Python golden boards", () => {
  assert.ok(goldens.length >= 30, "golden fixture present");
  let checked = 0;
  for (const [diff, seed, [r, c], boardLines, state] of goldens) {
    const b = new SimBoard();
    b.new(diff, BigInt(seed));
    b.click(r, c);
    assert.deepEqual(b.board(), boardLines, `board diff=${diff} seed=${seed} click=${r},${c}`);
    assert.equal(b.state().board, state.board, `state.board diff=${diff} seed=${seed}`);
    assert.equal(b.state().status, state.status, `state.status diff=${diff} seed=${seed}`);
    checked++;
  }
  assert.equal(checked, goldens.length);
});

test("R(-5)==R(5): negative seeds share key", () => {
  const a = new SimBoard();
  const b = new SimBoard();
  a.new("beginner", -5n);
  b.new("beginner", 5n);
  assert.deepEqual(a.board(), b.board());
});

test("seed 0 maps to the shared nonzero fallback (non-degenerate, cross-language)", () => {
  // xorshift64 with state 0 is the fixed point 0 -> 0 forever, so a zero seed
  // would collapse the RNG to a constant stream.  All three ports (C, Python,
  // Node) must instead substitute the same nonzero constant so a seed of 0
  // yields a real board that agrees everywhere.
  assert.notEqual(Rng64.prototype.next.call(new Rng64(0n)), 0n, "Rng64(0) first draw is nonzero");

  const z = new SimBoard();
  z.new("beginner", 0n);
  z.click(4, 4);
  assert.equal(z.seed, ZERO_SEED_FALLBACK, "reported seed is the fallback constant");
  assert.equal(z.state().seed, String(ZERO_SEED_FALLBACK), "state dump reports the fallback");
  assert.equal(z.state().seeded, "1");

  // Non-degenerate: a seed-0 board must differ from a seed-1 board once mines
  // are actually placed (a plain new() board is all-hidden, so click first).
  const one = new SimBoard();
  one.new("beginner", 1n);
  one.click(4, 4);
  assert.notDeepEqual(z.board(), one.board(), "seed-0 layout differs from seed-1 layout");

  // Cross-language identity: the golden fixture for seed 0 was generated by the
  // Python reference (server/sim_engine.py); Node must reproduce it exactly.
  const golden = goldens.find(
    ([diff, seed, pos]) => diff === "beginner" && seed === 0 && pos[0] === 4 && pos[1] === 4
  );
  assert.ok(golden, "golden fixture contains a beginner seed-0 entry");
  assert.equal(golden[4].seed, String(ZERO_SEED_FALLBACK), "Python fixture uses the same fallback");
  assert.deepEqual(z.board(), golden[3], "Node board matches the Python seed-0 golden");
  assert.equal(z.state().seed, golden[4].seed, "Node state matches the Python seed-0 golden");
});
