#!/usr/bin/env node
// parity-all.js - live Node <-> Python differential for the ms/ port.
//
// Re-verifies the three places where the port must be *exact* against the
// Python reference on every run (no frozen fixtures):
//
//   1. sim     - SimBoard board/state after click/flag/chord scripts, for
//                presets + custom sizes + negative/large seeds.
//   2. solve   - Board parse, buildConstraints, deduce, frontierProbabilities
//                and nonfrontierP on random mid-game boards (boards generated
//                by the same gen_board() as tools/analyze_diff.py).
//   3. backpressure - live scheduling differential: both sim servers (Python
//                and Node) driven over their real TCP entry points with the
//                same gated/queued load, asserting identical admission
//                decisions and backpressure contract (see backpressure-parity.js).
//
// The Python reference runs as a subprocess (ms/tools/py_ref.py); the boards
// for (2) are generated by Python so both runtimes solve identical input.
//
// Optional extras reported when the C tooling exists (they are also asserted
// by test/analyze.test.js and cli/verify-parity.js):
//   - analyze-diff.js  Node solver vs build/analyze_test.exe (C engine)
//   - verify-parity.js Node sim board vs real minesweeper-x64.exe --listen
//
// Exit code: 0 = all exact comparisons matched, 1 = any mismatch.
// Requires `python` on PATH for the Python side.

import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import { SimBoard } from "../core/sim-engine.js";
import { Random } from "../core/mt19937.js";
import {
  Board,
  buildConstraints,
  deduce,
  frontierProbabilities,
} from "../core/solver.js";
import { runDiff } from "../analyze/analyze-diff.js";
import { run as verifyRun } from "../cli/verify-parity.js";
import { main as backpressureMain } from "./backpressure-parity.js";

const here = path.dirname(fileURLToPath(import.meta.url));
const MS_DIR = path.dirname(here);
const REPO = path.dirname(MS_DIR);
const PY_REF = path.join(here, "py_ref.py");
const PYTHON = process.env.MS_PYTHON || "python";

const TOL = 1e-9;

// ---------------------------------------------------------------------------
// Python subprocess driver
// ---------------------------------------------------------------------------

function runPy(mode, payload) {
  const p = spawnSync(PYTHON, [PY_REF, mode], {
    cwd: REPO,
    input: JSON.stringify(payload) + "\n",
    encoding: "utf8",
  });
  if (p.error) throw p.error;
  if (p.status !== 0) {
    throw new Error(`py_ref ${mode} failed (${p.status}): ${p.stderr}`);
  }
  const replies = [];
  for (const line of p.stdout.split("\n")) {
    const t = line.trim();
    if (!t) continue;
    const parsed = JSON.parse(t);
    if (parsed.error) throw new Error(`py_ref ${mode}: ${parsed.error}`);
    replies.push(...parsed.reply);
  }
  return replies;
}

// ---------------------------------------------------------------------------
// 1. sim differential
// ---------------------------------------------------------------------------

function simScripts() {
  const scripts = [];
  const post = [
    { o: "flag", r: 3, c: 1 },
    { o: "click", r: 1, c: 3 },
    { o: "chord", r: 1, c: 1 },
    { o: "flag", r: 1, c: 1 },
    { o: "flag", r: 1, c: 1 },
    { o: "flag", r: 1, c: 1 },
  ];
  for (const diff of ["beginner", "intermediate", "expert"]) {
    for (const seed of ["0", "1", "12345", "9000", "-5", "18446744073709551615"]) {
      scripts.push([{ o: "new", d: diff, s: seed }, { o: "click", r: 1, c: 1 }, ...post]);
    }
  }
  scripts.push([
    { o: "new", d: "custom 6 7 5", s: "7" },
    { o: "click", r: 1, c: 1 },
    { o: "flag", r: 3, c: 1 },
    { o: "click", r: 1, c: 3 },
    { o: "chord", r: 1, c: 1 },
  ]);
  scripts.push([{ o: "new", d: "custom 3 3 8", s: "2" }, { o: "click", r: 1, c: 1 }]);
  scripts.push([{ o: "new", d: "custom 5 5 0", s: "3" }, { o: "click", r: 2, c: 2 }]);
  scripts.push([{ o: "new", d: "custom 2 2 1", s: "4" }, { o: "click", r: 1, c: 1 }, { o: "flag", r: 0, c: 0 }]);
  scripts.push([{ o: "new", d: "beginner", s: "5" }]);
  scripts.push([
    { o: "new", d: "beginner", s: "5" },
    { o: "click", r: 4, c: 4 },
    { o: "new", d: "beginner", s: "5" },
    { o: "click", r: 4, c: 4 },
  ]);
  return scripts;
}

function runSimNode(scripts) {
  const out = [];
  for (const script of scripts) {
    const b = new SimBoard();
    for (const op of script) {
      const o = op.o;
      if (o === "new") b.new(op.d, BigInt(op.s));
      else if (o === "click") b.click(op.r, op.c);
      else if (o === "flag") b.flag(op.r, op.c);
      else if (o === "chord") b.chord(op.r, op.c);
    }
    out.push({ board: b.board(), state: b.state() });
  }
  return out;
}

// ---------------------------------------------------------------------------
// 2. solve differential
// ---------------------------------------------------------------------------

function solveCases() {
  const cases = [];
  let id = 0;
  const rng = new Random(20260810);
  for (let t = 0; t < 26; t++) {
    const rows = rng.randint(4, 9);
    const cols = rng.randint(4, 9);
    cases.push({ id: String(id++), rng_seed: 1000 + t, rows, cols });
  }
  cases.push({ id: String(id++), rng_seed: 9001, rows: 10, cols: 12 });
  cases.push({ id: String(id++), rng_seed: 9002, rows: 12, cols: 20 });
  cases.push({ id: String(id++), rng_seed: 9003, rows: 16, cols: 30 });
  return cases;
}

function normCons(nodeCons) {
  return nodeCons.map(({ cells, need }) => [need, [...cells].sort((a, b) => a - b)]);
}

function solveNode(caseData) {
  const b = new Board(caseData.rows, caseData.lines, caseData.mines);
  const cons = buildConstraints(b);
  const { safes, mines } = deduce(b, cons);
  const { probs, nonfrontierP } = frontierProbabilities(b, cons);
  return {
    cons: normCons(cons),
    safe: [...safes].sort((a, b) => a - b),
    mine: [...mines].sort((a, b) => a - b),
    probs: [...probs.entries()].map(([c, p]) => [c, p]).sort((a, b) => a[0] - b[0]),
    nfp: nonfrontierP,
  };
}

// ---------------------------------------------------------------------------
// comparison helpers
// ---------------------------------------------------------------------------

let failures = 0;

function fail(msg) {
  failures += 1;
  console.log("  MISMATCH: " + msg);
}

function cmpArray(label, id, a, b, eq) {
  if (a.length !== b.length) {
    fail(`${label}[${id}] length ${a.length} vs ${b.length}`);
    return;
  }
  for (let i = 0; i < a.length; i++) {
    if (!eq(a[i], b[i])) {
      fail(`${label}[${id}] entry ${i}: ${JSON.stringify(a[i])} vs ${JSON.stringify(b[i])}`);
      return;
    }
  }
}

const exact = (x, y) => JSON.stringify(x) === JSON.stringify(y);
const probEq = (a, b) => a[0] === b[0] && Math.abs(a[1] - b[1]) <= TOL;
const num = (x, y) =>
  typeof x === "number" && typeof y === "number"
    ? Math.abs(x - y) <= TOL
    : x === null && y === null;

function compareSim(py, node) {
  const eqState = (a, b) => {
    const ka = Object.keys(a).sort();
    const kb = Object.keys(b).sort();
    if (JSON.stringify(ka) !== JSON.stringify(kb)) return false;
    for (const k of ka) if (a[k] !== b[k]) return false;
    return true;
  };
  for (let i = 0; i < py.length; i++) {
    cmpArray(`sim.board`, i, py[i].board, node[i].board, exact);
    if (!eqState(py[i].state, node[i].state)) {
      fail(`sim.state[${i}] ${JSON.stringify(py[i].state)} vs ${JSON.stringify(node[i].state)}`);
    }
  }
}

function compareSolve(py) {
  for (const caseData of py) {
    const node = solveNode(caseData);
    const id = caseData.id;
    cmpArray(`solve.cons`, id, caseData.cons, node.cons, exact);
    cmpArray(`solve.safe`, id, caseData.safe, node.safe, exact);
    cmpArray(`solve.mine`, id, caseData.mine, node.mine, exact);
    cmpArray(`solve.probs`, id, caseData.probs, node.probs, probEq);
    if (!num(caseData.nfp, node.nfp)) {
      fail(`solve.nfp[${id}] ${caseData.nfp} vs ${node.nfp}`);
    }
  }
}

export function checkPython() {
  const p = spawnSync(
    PYTHON,
    [
      "-c",
      "import random, sys; sys.path[:0]=['minesweeper_bot','server']; " +
        "import ms_solver, sim_engine",
    ],
    { cwd: REPO, encoding: "utf8" },
  );
  return p.error === undefined && p.status === 0;
}

export function runSimDiff() {
  const before = failures;
  const scripts = simScripts();
  const py = runPy("sim", { op: "sim", scripts });
  const node = runSimNode(scripts);
  compareSim(py, node);
  return { scripts: scripts.length, failures: failures - before };
}

export function runSolveDiff() {
  const before = failures;
  const cases = solveCases();
  const py = runPy("solve", { op: "solve", cases });
  compareSolve(py);
  return { boards: cases.length, failures: failures - before };
}

// ---------------------------------------------------------------------------
// optional C differentials (report only; asserted by the test suite too)
// ---------------------------------------------------------------------------

async function optionalC() {
  const analyzeExe = path.join(REPO, "build", "analyze_test.exe");
  if (fs.existsSync(analyzeExe)) {
    const res = runDiff(1, 25);
    console.log(`  analyze-diff (C exe): ${res.boards} boards, ${res.failures} mismatches`);
  } else {
    console.log("  analyze-diff (C exe): skipped (build/analyze_test.exe missing)");
  }
  const exe = fs.existsSync(path.join(REPO, "build", "minesweeper-x64.exe"))
    ? path.join(REPO, "build", "minesweeper-x64.exe")
    : fs.existsSync(path.join(REPO, "build", "minesweeper-x86.exe"))
      ? path.join(REPO, "build", "minesweeper-x86.exe")
      : null;
  if (exe) {
    const code = await verifyRun({ exe, fast: true, seeds: 8 });
    console.log(`  verify-parity (live exe): exit ${code}`);
  } else {
    console.log("  verify-parity (live exe): skipped (no minesweeper exe in build/)");
  }
}

// ---------------------------------------------------------------------------

export async function runAll() {
  console.log("parity-all: live Node <-> Python differential");
  console.log("  python = " + PYTHON);

  console.log("\n[1/4] sim engine");
  let sim, solve;
  try {
    sim = runSimDiff();
    console.log(`  sim: ${sim.scripts} scripts compared (boards + state)`);
  } catch (e) {
    fail("sim engine: " + (e && e.stack ? e.stack : e.message));
  }

  console.log("\n[2/4] solver");
  try {
    solve = runSolveDiff();
    console.log(`  solve: ${solve.boards} mid-game boards compared (cons/deduce/probs/nfp)`);
  } catch (e) {
    fail("solver: " + (e && e.stack ? e.stack : e.message));
  }

  console.log("\n[3/4] scheduling/backpressure differential (live servers)");
  try {
    const code = await backpressureMain();
    console.log(`  backpressure: exit ${code}`);
    if (code !== 0) fail("scheduling/backpressure differential failed");
  } catch (e) {
    fail("scheduling/backpressure differential: " + (e && e.stack ? e.stack : e.message));
  }

  console.log("\n[4/4] C differentials (informational)");
  try {
    await optionalC();
  } catch (e) {
    fail("optional C differential: " + (e && e.stack ? e.stack : e.message));
  }

  const ok = failures === 0;
  console.log(
    `\nparity-all: ${ok ? "PASS" : "FAIL"} (${failures} mismatch${failures === 1 ? "" : "es"})`
  );
  return { ok, failures };
}

const isMain =
  process.argv[1] !== undefined &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const { ok } = await runAll();
  process.exit(ok ? 0 : 1);
}
